# Generated by Django 4.2.5 on 2023-10-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='parent_section',
        ),
    ]
